---
- name: Ensure that the required role variable was provided
  ansible.builtin.assert:
    that:
      - wazuh_agent_manager is defined
    fail_msg: The wazuh_agent_manager role variable must be defined.

- name: Load tasks file based on the OS type
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - setup_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - setup_{{ ansible_distribution }}.yml
        - setup_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"

# XMLStarlet is used by cloud-init at startup time to inject the Wazuh
# agent name into the Wazuh XML configuration file.  See
# cisagov/cool-assessment-terraform for examples where this is done.
- name: Install XMLStarlet
  ansible.builtin.package:
    name: xmlstarlet

- name: Install the Wazuh agent
  ansible.builtin.package:
    name: wazuh-agent
  environment:
    WAZUH_MANAGER: "{{ wazuh_agent_manager }}"

- name: Enable the Wazuh agent systemd service
  ansible.builtin.systemd_service:
    # Unless you do this, systemd can sometimes get confused when you
    # try to start a service you just installed.
    daemon_reload: true
    enabled: true
    name: wazuh-agent

- name: Install wazuh-agent service drop-in
  block:
    - name: >-
        Ensure that the directory where the wazuh-agent service
        drop-in will live actually exists
      ansible.builtin.file:
        group: root
        mode: u=rwx,g=rx,o=rx
        owner: root
        path: /etc/systemd/system/wazuh-agent.service.d
        state: directory

    # This drop-in contains our local overrides for the wazuh-agent
    # systemd service.
    - name: Create the drop-in unit file
      ansible.builtin.copy:
        dest: /etc/systemd/system/wazuh-agent.service.d/wazuh-agent.conf
        group: root
        mode: u=rw,g=r,o=r
        owner: root
        src: wazuh-agent.service
        # It would be great to use systemd-analyze verify here, but
        # that won't work.  See, for instance, this GitHub issue
        # comment:
        # https://github.com/ansible/ansible/issues/19243#issuecomment-266508074
        # validate: /usr/bin/systemd-analyze verify %s

    - name: Systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
