---
- name: Ensure that the required role variable was provided
  ansible.builtin.assert:
    that:
      - wazuh_agent_manager is defined
    fail_msg: The wazuh_agent_manager role variable must be defined.

- name: Load tasks file based on the OS type
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - setup_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - setup_{{ ansible_distribution }}.yml
        - setup_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"

# XMLStarlet is used by cloud-init at startup time to inject the Wazuh
# agent name into the Wazuh XML configuration file.  See
# cisagov/cool-assessment-terraform for examples where this is done.
- name: Install XMLStarlet
  ansible.builtin.package:
    name: xmlstarlet

- name: Install the Wazuh agent
  ansible.builtin.package:
    name: wazuh-agent
  environment:
    WAZUH_MANAGER: "{{ wazuh_agent_manager }}"

- name: Perform a systemd daemon-reload
  ansible.builtin.systemd_service:
    # Unless you do this, systemd can sometimes get confused when you
    # try to enable or start a service you just installed.
    daemon_reload: true

# Note that we do not enable or start the service here.  This is done
# by cloud-init after the Wazuh agent name has been injected into the
# Wazuh configuration file.
