---
# Setup for installing Wazuh agent on RedHat from the official Wazuh
# repo.
#
# https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html

- name: Install gnupg2 (necessary for RPM repo GPG key manipulations)
  ansible.builtin.package:
    name:
      - gnupg2
  when:
    # AL2023 already has a package installed called gnupg2-minimal
    # that conflicts with gnupg2.
    - ansible_distribution != "Amazon"

- name: Import Wazuh RPM GPG key
  ansible.builtin.rpm_key:
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: Add the official Wazuh repo
  ansible.builtin.yum_repository:
    baseurl: https://packages.wazuh.com/4.x/yum/
    description: Wazuh package repo
    gpgcheck: true
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    name: wazuh
    priority: "1"
  notify:
    - Update the package cache

# We need the handler that updates the RPM package cache to run
# now if it is necessary.  It is required by the parent playbook
# since it will attempt to install the packages from the new RPM
# package repo.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
